title: "bock :: Maths m -> CompSci s -> Maybe Result r"
email: me@andreasbock.dk
domain: andreasbock.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://andreasbock.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: aa_bock
github_username:  andreasbock


# Build settings
theme: minima
plugins:
  - jekyll-feed

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: aa_bock
    github:  andreasbock
    linkedin: andreas-bock

collections:
  - news